version: '3.8'

services:
  charger-base:
    image: obazda/pi_temperature_sensor:${BASE_VERSION:-0.1}-${BASE_ARCH:-AMD64}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - /sys/devices:/sensors
    environment:
      - ROOT_DIR=${ROOT_DIR:-/sensors}
      - SENSOR_FILENAME=${SENSOR_FILENAME:-w1_slave}
      - INTERVAL=${INTERVAL:-1}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
